worker_processes auto;

events {
  worker_connections 1024;
}

http {
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log warn;

  upstream backend_pool {
    # Aktive Strategie: Weighted Round Robin.
    # web-a ist schneller und erhält deshalb ein höheres Gewicht.
    #
    # Zum Testen anderer Strategien genau eine der nächsten Zeilen aktivieren:
    # least_conn;
    # ip_hash;
    # hash $request_uri consistent;

    server web-a:8000 weight=3 max_fails=2 fail_timeout=5s;
    server web-b:8000 weight=1 max_fails=2 fail_timeout=5s;
    server web-c:8000 weight=1 max_fails=2 fail_timeout=5s;
  }

  server {
    listen 80;

    location /health {
      add_header Content-Type text/plain;
      return 200 "load-balancer ok\n";
    }

    location / {
      proxy_pass http://backend_pool;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_connect_timeout 2s;
      proxy_read_timeout 6s;
      proxy_next_upstream error timeout http_502 http_503 http_504;
    }
  }
}
