apiVersion: 1

prune: true

datasources:
  - name: MQTT
    uid: mqtt
    type: grafana-mqtt-datasource
    access: proxy
    orgId: 1
    isDefault: true
    editable: true
    jsonData:
      uri: tcp://mosquitto:1883
      clientID: grafana-smarthome
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: false
